# Generated by Django 2.1.7 on 2019-06-11 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelineapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='table',
            new_name='schedule',
        ),
    ]
